config/routes.rb
Rails.application.routes.draw do
	root 'home#index'


	get 'skills', to: 'home#skills'
	get 'education', to: 'home#education'
	get 'experience', to: 'home#experience'
	get 'portfolio', to: 'home#portfolio'
	get 'testimonials', to: 'home#testimonials'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end

	def skills
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def is_active?(path)
		return 'active' if action_name == path
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_nav.html.erb
<header class="header_area">

	<div class="logo d-flex justify-content-center align-items-center">
		<a href=<%= root_path %>>
			<img src="img/core-img/logo2.png" alt="">
		</a>

		<div class="nav-toggle">
			<i class="fa fa-bars"></i>
		</div>
	</div>

	<ul class="vcard-nav">
		<li class=<%= is_active?('index') %>>
			<%= link_to 'About', root_path %>
		</li>

		<li class=<%= is_active?('skills') %>>
			<%= link_to 'Skills', skills_path %>
		</li>

		<li class=<%= is_active?('experience') %>>
			<%= link_to 'Experience', experience_path %>
		</li>

		<li class=<%= is_active?('education') %>>
			<%= link_to 'Education', education_path %>
		</li>

		<li class=<%= is_active?('portfolio') %>>
			<%= link_to 'Portfolio', portfolio_path %>
		</li>

		<li class=<%= is_active?('testimonials') %>>
			<%= link_to 'Testimonials', testimonials_path %>
		</li>
	</ul>

</header>

app/views/home/education.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="description" content="">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


<title>Vcard - Resume CV &amp; Vcard Template</title>

<link rel="icon" href="img/core-img/favicon.ico">

<link rel="stylesheet" href="style.css">
</head>
<body>

<div id="preloader">
<div class="loader"></div>
</div>
<div class="vcard-main-wrapper">
<div class="vcard-content-wrapper bg-img" style="background-image: url(img/bg-img/bg6.jpg);">

<div class="horizontal-contact-btn">
<a href="#" class="btn vcard-btn contact-btn"><i class="fa fa-envelope-o"></i><span>Available for freelance work</span></a>
</div>

<header class="header_area">

<div class="logo d-flex justify-content-center align-items-center">
<a href="index-horizontal-about.html"><img src="img/core-img/logo2.png" alt=""></a>

<div class="nav-toggle">
<i class="fa fa-bars"></i>
</div>
</div>

<ul class="vcard-nav">
<li><a href="index-horizontal-about.html">About</a></li>
<li><a href="index-horizontal-skills.html">Skills</a></li>
<li><a href="index-horizontal-services.html">Services</a></li>
<li><a href="index-horizontal-experience.html">Experience</a></li>
<li class="active"><a href="index-horizontal-education.html">Education</a></li>
<li><a href="index-horizontal-portfolio.html">Portfolio</a></li>
<li><a href="index-horizontal-testimonials.html">Testimonials</a></li>
<li><a href="index-horizontal-contact.html">Contact</a></li>
</ul>
</header>

<div class="vcard-page-content-wrapper d-flex align-items-end">
<div class="page-content">

<div class="education-area">
<div class="container-fluid">
<div class="row">

<div class="col-12">
<div class="section-heading">
<h2>Education</h2>
</div>
</div>
</div>
<div class="row">
<div class="col-12">
<div class="education-timeline-wrapper">

<div class="timeline-row"></div>

<div class="single-education-timeline d-flex active odd-item">
<div class="education-icon mr-15">
<img src="img/core-img/edu1.png" alt="">
</div>
<div class="education-content">
<h5>2015-Present</h5>
<h4>Art Director</h4>
<h6>Company INC</h6>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu metus sit amet odio sodales placerat. Sed varius leo ac leo fermentum, eu cursus nunc.</p>
</div>
</div>

<div class="single-education-timeline d-flex even-item">
<div class="education-icon mr-15">
<img src="img/core-img/edu2.png" alt="">
</div>
<div class="education-content">
<h5>2015-Present</h5>
<h4>Art Director</h4>
<h6>Company INC</h6>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu metus sit amet odio sodales placerat. Sed varius leo ac leo fermentum, eu cursus nunc.</p>
</div>
</div>

<div class="single-education-timeline d-flex odd-item">
<div class="education-icon mr-15">
<img src="img/core-img/edu3.png" alt="">
</div>
<div class="education-content">
<h5>2015-Present</h5>
<h4>Art Director</h4>
<h6>Company INC</h6>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu metus sit amet odio sodales placerat. Sed varius leo ac leo fermentum, eu cursus nunc.</p>
</div>
</div>

<div class="single-education-timeline d-flex even-item">
<div class="education-icon mr-15">
<img src="img/core-img/edu4.png" alt="">
</div>
<div class="education-content">
<h5>2015-Present</h5>
<h4>Art Director</h4>
<h6>Company INC</h6>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu metus sit amet odio sodales placerat. Sed varius leo ac leo fermentum, eu cursus nunc.</p>
</div>
</div>
</div>
</div>
</div>
<p class="mt-5"><a href="#">
Copyright &copy;<script type="6d6e02f612ce7ae5d19c41e7-text/javascript">document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
</p>
</div>
</div>
</div>
</div>
</div>
</div>


<script src="js/jquery/jquery-2.2.4.min.js" type="6d6e02f612ce7ae5d19c41e7-text/javascript"></script>

<script src="js/bootstrap/popper.min.js" type="6d6e02f612ce7ae5d19c41e7-text/javascript"></script>

<script src="js/bootstrap/bootstrap.min.js" type="6d6e02f612ce7ae5d19c41e7-text/javascript"></script>

<script src="js/plugins/plugins.js" type="6d6e02f612ce7ae5d19c41e7-text/javascript"></script>

<script src="js/active.js" type="6d6e02f612ce7ae5d19c41e7-text/javascript"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="6d6e02f612ce7ae5d19c41e7-text/javascript"></script>
<script type="6d6e02f612ce7ae5d19c41e7-text/javascript">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="6d6e02f612ce7ae5d19c41e7-|49" defer=""></script></body>
</html>

app/views/home/experience.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="description" content="">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


<title>Vcard - Resume CV &amp; Vcard Template</title>

<link rel="icon" href="img/core-img/favicon.ico">

<link rel="stylesheet" href="style.css">
</head>
<body>

<div id="preloader">
<div class="loader"></div>
</div>
<div class="vcard-main-wrapper">
<div class="vcard-content-wrapper bg-img" style="background-image: url(img/bg-img/bg5.jpg);">

<div class="horizontal-contact-btn">
<a href="#" class="btn vcard-btn contact-btn"><i class="fa fa-envelope-o"></i><span>Available for freelance work</span></a>
</div>

<header class="header_area">

<div class="logo d-flex justify-content-center align-items-center">
<a href="index-horizontal-about.html"><img src="img/core-img/logo2.png" alt=""></a>

<div class="nav-toggle">
<i class="fa fa-bars"></i>
</div>
</div>

<ul class="vcard-nav">
<li><a href="index-horizontal-about.html">About</a></li>
<li><a href="index-horizontal-skills.html">Skills</a></li>
<li><a href="index-horizontal-services.html">Services</a></li>
<li class="active"><a href="index-horizontal-experience.html">Experience</a></li>
<li><a href="index-horizontal-education.html">Education</a></li>
<li><a href="index-horizontal-portfolio.html">Portfolio</a></li>
<li><a href="index-horizontal-testimonials.html">Testimonials</a></li>
<li><a href="index-horizontal-contact.html">Contact</a></li>
</ul>
</header>

<div class="vcard-page-content-wrapper d-flex align-items-end">
<div class="page-content">

<div class="work-experience-area">
<div class="container-fluid">
<div class="row">

<div class="col-12">
<div class="section-heading">
<h2>Work Experience</h2>
</div>
</div>
</div>
<div class="row">
<div class="col-12">
<div class="work-experience-timeline-wrapper">

<div class="timeline-row"></div>

<div class="single-experience-timeline active odd-item">
<h5>2015-Present</h5>
<h4>Art Director</h4>
<h6>Company INC</h6>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu metus sit amet odio sodales placerat. Sed varius leo ac leo fermentum, eu cursus nunc.</p>
</div>

<div class="single-experience-timeline even-item">
<h5>2013-2015</h5>
<h4>Senior Digital Designer</h4>
<h6>Company INC</h6>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu metus sit amet odio sodales placerat. Sed varius leo ac leo fermentum, eu cursus nunc.</p>
</div>

<div class="single-experience-timeline odd-item">
<h5>2010-2013</h5>
<h4>Digital Designer</h4>
<h6>Company INC</h6>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu metus sit amet odio sodales placerat. Sed varius leo ac leo fermentum, eu cursus nunc.</p>
</div>

<div class="single-experience-timeline even-item">
<h5>2015-Present</h5>
<h4>Junior Digital Designer</h4>
<h6>Company INC</h6>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu metus sit amet odio sodales placerat. Sed varius leo ac leo fermentum, eu cursus nunc.</p>
</div>
</div>
</div>
</div>
</div>
<p class="mt-5"><a href="#">
Copyright &copy;<script type="d7df030591590befb19df023-text/javascript">document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
</p>
</div>
</div>
</div>
</div>
</div>


<script src="js/jquery/jquery-2.2.4.min.js" type="d7df030591590befb19df023-text/javascript"></script>

<script src="js/bootstrap/popper.min.js" type="d7df030591590befb19df023-text/javascript"></script>

<script src="js/bootstrap/bootstrap.min.js" type="d7df030591590befb19df023-text/javascript"></script>

<script src="js/plugins/plugins.js" type="d7df030591590befb19df023-text/javascript"></script>

<script src="js/active.js" type="d7df030591590befb19df023-text/javascript"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="d7df030591590befb19df023-text/javascript"></script>
<script type="d7df030591590befb19df023-text/javascript">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="d7df030591590befb19df023-|49" defer=""></script></body>
</html>

app/views/home/index.html.erb
<div class="vcard-main-wrapper">
<div class="vcard-content-wrapper bg-img" style="background-image: url(img/bg-img/bg3.jpg);">

<%= render "nav"%>


<div class="vcard-page-content-wrapper d-flex align-items-end">
<div class="page-content">

<div class="hero-area horizontal clearfix">
<div class="hero-content">
<h5>Hello I am</h5>
<h2>Justas Tamulionis</h2>
<h3>Web developer &amp; Cyberpunk</h3>

<div class="contact-info mt-30">
<a href="#">
	<img src="img/core-img/envelope2.png" alt=""> 
	<span class="__cf_email__">justas.tamulionis@gmail.com</span>
</a>
<a href="#"><img src="img/core-img/phone-call2.png" alt=""> +3706 92 44 894</a>
</div>

<div class="social-info mt-30">
<a id="btn_facebook" href="https://www.facebook.com/justas.tamulionis" title="Facebook" target="_blank"></a>
<a id="btn_instagram" href="https://www.instagram.com/big.dzy" title="Instagram" target="_blank"></a>
<a id="btn_linkedin" href="https://www.linkedin.com/in/justas-tamulionis" title="Linkedin" target="_blank"></a>
<a id="btn_youtube" href="https://www.youtube.com/channel/UCV7w_mLJEpnxAee-WqGqiOQ?view_as=subscriber" title="Youtube" target="_blank"></a>


</div>
</div>

</div>
</div>
</div>
</div>
</div>

app/views/home/portfolio.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="description" content="">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


<title>Vcard - Resume CV &amp; Vcard Template</title>

<link rel="icon" href="img/core-img/favicon.ico">

<link rel="stylesheet" href="style.css">
</head>
<body>

<div id="preloader">
<div class="loader"></div>
</div>
<div class="vcard-main-wrapper">
<div class="vcard-content-wrapper bg-img">

<div class="horizontal-contact-btn">
<a href="#" class="btn vcard-btn contact-btn"><i class="fa fa-envelope-o"></i><span>Available for freelance work</span></a>
</div>

<header class="header_area">

<div class="logo d-flex justify-content-center align-items-center">
<a href="index-horizontal-about.html"><img src="img/core-img/logo2.png" alt=""></a>

<div class="nav-toggle">
<i class="fa fa-bars"></i>
</div>
</div>

<ul class="vcard-nav">
<li><a href="index-horizontal-about.html">About</a></li>
<li><a href="index-horizontal-skills.html">Skills</a></li>
<li><a href="index-horizontal-services.html">Services</a></li>
<li><a href="index-horizontal-experience.html">Experience</a></li>
<li><a href="index-horizontal-education.html">Education</a></li>
<li class="active"><a href="index-horizontal-portfolio.html">Portfolio</a></li>
<li><a href="index-horizontal-testimonials.html">Testimonials</a></li>
<li><a href="index-horizontal-contact.html">Contact</a></li>
</ul>
</header>

<div class="vcard-page-content-wrapper d-flex align-items-end">
<div class="page-content">

<div class="portfolio-area clearfix">
<div class="container-fluid">
<div class="row">
<div class="col-12">
<div class="vcard-projects-menu">
<div class="portfolio-menu">
<button class="btn active" data-filter="*">Digital Design</button>
<button class="btn" data-filter=".web">Web Design</button>
<button class="btn" data-filter=".brand">Brand Identity</button>
<button class="btn" data-filter=".illustrations">Illustrations</button>
<button class="btn" data-filter=".motion">Motion Graphics</button>
</div>
</div>
</div>
</div>
</div>
<div class="container-fluid">
<div class="row vcard-portfolio">

<div class="col-12 col-sm-6 col-xl-4 single-portfolio-area web brand">
<img src="img/bg-img/p1.jpg" alt="">

<div class="portfolio-content">
<h5>Brand identity - Company</h5>
<a href="#" class="catagory">Branding</a>

<div class="vcard-img-zoom">
<a href="img/bg-img/p1.jpg" class="img-url"><i class="fa fa-search-plus" aria-hidden="true"></i></a>
</div>
</div>
</div>

<div class="col-12 col-sm-6 col-xl-4 single-portfolio-area brand illustrations">
<img src="img/bg-img/p2.jpg" alt="">

<div class="portfolio-content">
<h5>Device Mockup</h5>
<a href="#" class="catagory">Digital Design</a>

 <div class="vcard-img-zoom">
<a href="img/bg-img/p2.jpg" class="img-url"><i class="fa fa-search-plus" aria-hidden="true"></i></a>
</div>
</div>
</div>

<div class="col-12 col-sm-6 col-xl-4 single-portfolio-area web illustrations">
<img src="img/bg-img/p3.jpg" alt="">

<div class="portfolio-content">
<h5>Brand identity - Company</h5>
<a href="#" class="catagory">Digital Design</a>

<div class="vcard-img-zoom">
<a href="img/bg-img/p3.jpg" class="img-url"><i class="fa fa-search-plus" aria-hidden="true"></i></a>
</div>
</div>
</div>

<div class="col-12 col-sm-6 col-xl-4 single-portfolio-area brand motion">
<img src="img/bg-img/p4.jpg" alt="">

<div class="portfolio-content">
<h5>Device Mockup</h5>
<a href="#" class="catagory">Digital Design</a>

<div class="vcard-img-zoom">
<a href="img/bg-img/p4.jpg" class="img-url"><i class="fa fa-search-plus" aria-hidden="true"></i></a>
</div>
</div>
</div>

<div class="col-12 col-sm-6 col-xl-4 single-portfolio-area brand motion">
<img src="img/bg-img/p6.jpg" alt="">

<div class="portfolio-content">
<h5>Brand identity - Company</h5>
<a href="#" class="catagory">Digital Design</a>

<div class="vcard-img-zoom">
<a href="img/bg-img/p6.jpg" class="img-url"><i class="fa fa-search-plus" aria-hidden="true"></i></a>
</div>
</div>
</div>

<div class="col-12 col-sm-6 col-xl-4 single-portfolio-area web motion">
<img src="img/bg-img/p8.jpg" alt="">

<div class="portfolio-content">
<h5>Device Mockup</h5>
<a href="#" class="catagory">Digital Design</a>

<div class="vcard-img-zoom">
<a href="img/bg-img/p8.jpg" class="img-url"><i class="fa fa-search-plus" aria-hidden="true"></i></a>
</div>
</div>
</div>

<div class="col-12 col-sm-6 col-xl-4 single-portfolio-area illustrations motion">
<img src="img/bg-img/p5.jpg" alt="">

<div class="portfolio-content">
<h5>Brand identity - Company</h5>
<a href="#" class="catagory">Digital Design</a>

<div class="vcard-img-zoom">
<a href="img/bg-img/p5.jpg" class="img-url"><i class="fa fa-search-plus" aria-hidden="true"></i></a>
</div>
</div>
</div>

<div class="col-12 col-sm-6 col-xl-4 single-portfolio-area illustrations motion">
<img src="img/bg-img/p7.jpg" alt="">

<div class="portfolio-content">
<h5>Device Mockup</h5>
<a href="#" class="catagory">Digital Design</a>

<div class="vcard-img-zoom">
<a href="img/bg-img/p7.jpg" class="img-url"><i class="fa fa-search-plus" aria-hidden="true"></i></a>
</div>
</div>
</div>

<div class="col-12 col-sm-6 col-xl-4 single-portfolio-area web motion">
<img src="img/bg-img/p9.jpg" alt="">

<div class="portfolio-content">
<h5>Device Mockup</h5>
<a href="#" class="catagory">Digital Design</a>

<div class="vcard-img-zoom">
<a href="img/bg-img/p9.jpg" class="img-url"><i class="fa fa-search-plus" aria-hidden="true"></i></a>
</div>
</div>
</div>
</div>

<div class="row">
<div class="col-12">
<div class="see-more mt-70 text-center mb-100">
<a href="#" class="btn vcard-btn">See Portfolio</a>
</div>
</div>
</div>
<p class="mt-5"><a href="#">
Copyright &copy;<script type="700ff45722224d97fae9b438-text/javascript">document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
</p>
</div>
</div>

</div>
</div>
</div>
</div>


<script src="js/jquery/jquery-2.2.4.min.js" type="700ff45722224d97fae9b438-text/javascript"></script>

 <script src="js/bootstrap/popper.min.js" type="700ff45722224d97fae9b438-text/javascript"></script>

<script src="js/bootstrap/bootstrap.min.js" type="700ff45722224d97fae9b438-text/javascript"></script>

<script src="js/plugins/plugins.js" type="700ff45722224d97fae9b438-text/javascript"></script>

<script src="js/active.js" type="700ff45722224d97fae9b438-text/javascript"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="700ff45722224d97fae9b438-text/javascript"></script>
<script type="700ff45722224d97fae9b438-text/javascript">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="700ff45722224d97fae9b438-|49" defer=""></script></body>
</html>

app/views/home/skills.html.erb
<div class="vcard-main-wrapper">
<div class="vcard-content-wrapper bg-img" style="background-image: url(img/bg-img/bg2.jpg);">

<%= render "nav"%>

<div class="vcard-page-content-wrapper d-flex align-items-end">
<div class="page-content">

<div class="about-me-area section-padding-100 clearfix">
<div class="container-fluid">
<div class="row align-items-end">
<div class="col-12 col-xl-6">
<div class="about-me-text">
<h2>Creative &amp; Commited</h2>
<h6>Nam id congue lectus, a venenatis massa. Maecenas justo libero, vulputate vel nunc id, blandit feugiat sem. Mauris impe rdiet, neque ornare varius.</h6>
</div>
</div>
<div class="col-12 col-xl-6">
<div class="about-me-text">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu metus sit amet odio sodales placerat. Sed varius leo ac leo fermentum, eu cursus nunc maximus. Integer convallis nisi nibh, et ornare neque ullamcorper ac. Nam id congue lectus, a venenatis massa. Maecenas justo libero, vulputate vel nunc id, blandit feugiat sem. Mauris imperdiet, neque ornare varius mattis.</p>
</div>
</div>
</div>
</div>
</div>
 

<div class="skills-area clearfix">
<div class="container-fluid">
<div class="row">

<div class="col-12 col-md-6 col-xl-3">
<div class="single-skils-area mb-100">
<div id="circle" class="circle" data-value="0.75">
<span>75%</span>
</div>
<div class="skills-text">
<h6>Photos Taken</h6>
<p>Etiam nec odio vestibulum est.</p>
</div>
</div>
</div>

<div class="col-12 col-md-6 col-xl-3">
<div class="single-skils-area mb-100">
<div id="circle2" class="circle" data-value="0.83">
<span>83%</span>
</div>
<div class="skills-text">
<h6>Digital Design</h6>
<p>Odio vestibulum est mattis.</p>
</div>
</div>
</div>

<div class="col-12 col-md-6 col-xl-3">
<div class="single-skils-area mb-100">
<div id="circle3" class="circle" data-value="0.25">
<span>25%</span>
</div>
<div class="skills-text">
<h6>HTML Coding</h6>
<p>Vestibulum est mattis effic.</p>
</div>
</div>
</div>

<div class="col-12 col-md-6 col-xl-3">
<div class="single-skils-area mb-100">
<div id="circle4" class="circle" data-value="0.95">
<span>95%</span>
</div>
<div class="skills-text">
<h6>Ilustrations</h6>
<p>Vestibulum est mattis effic.</p>
</div>
</div>
</div>
</div>
</div>
</div>


</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Justas Tamulionis - Resume CV</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />

    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>